{
  "formatVersion": "1.1",
  "component": {
    "group": "UploadApk-Plugin",
    "module": "upload-apk-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "upload-apk-plugin-unspecified.jar",
          "url": "upload-apk-plugin-unspecified.jar",
          "size": 91434,
          "sha512": "cc0d9655497fbe1367f00d2947fe6b0f3d542a04b53fb880c640fef1fcf6af55cef74c3b8036481ee9ed9050a221b52cd06d919288ab4eb5b2a1f8f426e80dd4",
          "sha256": "8d7d8e2c8ad7b294659756cb0ad7e8d707c23ebfa61b506f89558df8be792c39",
          "sha1": "e398833db81858aa398cd88f34a308649dbe3cca",
          "md5": "d492484dc71ca396bdfb389bb7ef8c5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "upload-apk-plugin-unspecified.jar",
          "url": "upload-apk-plugin-unspecified.jar",
          "size": 91434,
          "sha512": "cc0d9655497fbe1367f00d2947fe6b0f3d542a04b53fb880c640fef1fcf6af55cef74c3b8036481ee9ed9050a221b52cd06d919288ab4eb5b2a1f8f426e80dd4",
          "sha256": "8d7d8e2c8ad7b294659756cb0ad7e8d707c23ebfa61b506f89558df8be792c39",
          "sha1": "e398833db81858aa398cd88f34a308649dbe3cca",
          "md5": "d492484dc71ca396bdfb389bb7ef8c5d"
        }
      ]
    }
  ]
}
