{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.andzhang.android",
    "module": "upload-apk-plugin",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "upload-apk-plugin-1.2.0.jar",
          "url": "upload-apk-plugin-1.2.0.jar",
          "size": 91947,
          "sha512": "b6a8f9aa44858601cf8b47f8bcbc49d56eefec0ded8d484ead1a2d13c0001627a251eadaaff50f07f2528334d56f1d07ea46eceaabd8f8b279b53d8c79e8781e",
          "sha256": "46a7191c8973e65ba3da1f3d7a936f242747ec3226cda3e99c341b3b0c69b09c",
          "sha1": "2e3eadd37e33ce068b03667029704f5377a186a9",
          "md5": "0078c86bd3662d0a75737e1c72a7fbf7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "upload-apk-plugin-1.2.0.jar",
          "url": "upload-apk-plugin-1.2.0.jar",
          "size": 91947,
          "sha512": "b6a8f9aa44858601cf8b47f8bcbc49d56eefec0ded8d484ead1a2d13c0001627a251eadaaff50f07f2528334d56f1d07ea46eceaabd8f8b279b53d8c79e8781e",
          "sha256": "46a7191c8973e65ba3da1f3d7a936f242747ec3226cda3e99c341b3b0c69b09c",
          "sha1": "2e3eadd37e33ce068b03667029704f5377a186a9",
          "md5": "0078c86bd3662d0a75737e1c72a7fbf7"
        }
      ]
    }
  ]
}
