{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.andzhang.android",
    "module": "upload-apk-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "upload-apk-plugin-1.0.0.jar",
          "url": "upload-apk-plugin-1.0.0.jar",
          "size": 91951,
          "sha512": "97d42123eb5c6a5762d82cea793573e8f274574a3ab0a3ed2302301dc4bb598b1dd1b4cc3d0413e9c32847b5fe813864a5432981d79afcbb77dc0ede836e05e8",
          "sha256": "90d9779ab98742ac305eb73528f080100e7ce08174cbdd508c94506cecc54034",
          "sha1": "6c722b6155580a7ff6b0d1a75e44499a42c44111",
          "md5": "25f3cfe88e7b7d1fe177c0b50606ab07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "upload-apk-plugin-1.0.0.jar",
          "url": "upload-apk-plugin-1.0.0.jar",
          "size": 91951,
          "sha512": "97d42123eb5c6a5762d82cea793573e8f274574a3ab0a3ed2302301dc4bb598b1dd1b4cc3d0413e9c32847b5fe813864a5432981d79afcbb77dc0ede836e05e8",
          "sha256": "90d9779ab98742ac305eb73528f080100e7ce08174cbdd508c94506cecc54034",
          "sha1": "6c722b6155580a7ff6b0d1a75e44499a42c44111",
          "md5": "25f3cfe88e7b7d1fe177c0b50606ab07"
        }
      ]
    }
  ]
}
